In [3]:
import pandas as pd
import numpy as np
from datetime import datetime

In [11]:
spy = pd.read_csv("SPY.csv")
qqq = pd.read_csv("QQQ.csv")

In [12]:
spy.name = 'spy'
qqq.name = 'qqq'

def dayofweek_returns_singlefunc(symbol, aggfunc):
    symbol['Date'] = pd.to_datetime(symbol['Date'])
    label = symbol.name.upper() + ' Avg Daily Return %'
    symbol[label] = (symbol['Close']/symbol['Open'])-1
    grouped_returns = symbol.groupby(symbol.Date.dt.dayofweek)[label]
    grouped_returns = grouped_returns.apply(aggfunc)
    grouped_returns=grouped_returns.to_frame()
    grouped_returns= grouped_returns.rename_axis('Days of the Week')
    grouped_returns = grouped_returns.set_index(pd.Index(["Monday","Tuesday","Wednesday","Thursday","Friday"]))
    grouped_returns[label]=grouped_returns[label].apply(lambda x:'{:.3%}'.format(x))
    return grouped_returns

In [27]:
dayofweek_returns_singlefunc(spy,np.mean)

          SPY Avg Daily Return %
Monday                  0.012%
Tuesday                 0.001%
Wednesday               0.023%
Thursday                0.005%
Friday                 -0.016%

In [26]:
dayofweek_returns_singlefunc(qqq,np.mean)

          QQQ Avg Daily Return %
Monday                  0.004%
Tuesday                -0.046%
Wednesday               0.037%
Thursday                0.050%
Friday                 -0.067%

In [17]:
pd.set_option('display.max_colwidth', 20)
def dayofweek_returns_stats(symbol, aggfunc):
    symbol['Date'] = pd.to_datetime(symbol['Date'])
    symbol['Daily Return %'] = (symbol['Close']/symbol['Open'])-1
    grouped_returns = symbol.groupby(symbol.Date.dt.dayofweek)["Daily Return %"]
    grouped_returns = grouped_returns.apply(aggfunc)
    if aggfunc.__name__ == 'amin':
        column_name = "Minimum" + ' Daily Return %'
    elif aggfunc.__name__ == 'amax':
        column_name = "Maximum" + ' Daily Return %'
    elif aggfunc.__name__ == 'median':
        column_name = "Median Daily Return %"
    else:
        column_name = aggfunc.__name__.capitalize() + ' Daily Return %'
    grouped_returns = grouped_returns.to_frame(name=column_name)
    grouped_returns = grouped_returns.rename_axis('Days of the Week')
    grouped_returns = grouped_returns.set_index(pd.Index(["Monday","Tuesday","Wednesday","Thursday","Friday"]))
    grouped_returns[column_name] = grouped_returns[column_name].apply(lambda x: '{:.3%}'.format(x))
    # Count the number of up and down days and add them as new columns
    up_days = symbol[symbol['Daily Return %'] > 0].groupby(symbol.Date.dt.dayofweek)['Daily Return %'].count()
    down_days = symbol[symbol['Daily Return %'] < 0].groupby(symbol.Date.dt.dayofweek)['Daily Return %'].count()
    grouped_returns['Up Days'] = up_days.values
    grouped_returns['Down Days'] = down_days.values
    # Calculate the total number of days for each day of the week
    total_days = symbol.groupby(symbol.Date.dt.dayofweek)['Daily Return %'].size()
    grouped_returns['Total Days'] = total_days.values
    # Calculate the percentage of up and down days
    grouped_returns['% Up Days'] = grouped_returns['Up Days']/ grouped_returns['Total Days']
    grouped_returns['% Up Days'] = grouped_returns['% Up Days'].apply(lambda x: '{:.2%}'.format(x))
    grouped_returns['% Down Days'] = grouped_returns['Down Days']/ grouped_returns['Total Days']
    grouped_returns['% Down Days'] = grouped_returns['% Down Days'].apply(lambda x: '{:.2%}'.format(x))
    return grouped_returns

In [25]:
dayofweek_returns_stats(spy,np.mean)

,Mean Daily Return %,Up Days,Down Days,Total Days,% Up Days,% Down Days
Monday,0.012%,753,655,1427,52.77%,45.90%
Tuesday,0.001%,794,746,1559,50.93%,47.85%
Wednesday,0.023%,836,707,1558,53.66%,45.38%
Thursday,0.005%,796,719,1530,52.03%,46.99%
Friday,-0.016%,780,724,1520,51.32%,47.63%

In [24]:
dayofweek_returns_stats(qqq,np.mean)

,Mean Daily Return %,Up Days,Down Days,Total Days,% Up Days,% Down Days
Monday,0.004%,597,528,1135,52.60%,46.52%
Tuesday,-0.046%,644,585,1241,51.89%,47.14%
Wednesday,0.037%,652,580,1242,52.50%,46.70%
Thursday,0.050%,663,545,1221,54.30%,44.64%
Friday,-0.067%,598,606,1213,49.30%,49.96%

In [19]:
def dayofweek_returns_all_stats(symbol):
    symbol['Date'] = pd.to_datetime(symbol['Date'])
    symbol['Daily Return %'] = (symbol['Close']/symbol['Open'])-1
    grouped_returns = symbol.groupby(symbol.Date.dt.dayofweek)["Daily Return %"]
    aggfuncs = [np.mean, np.max, np.min, np.median]
    grouped_returns = grouped_returns.agg(aggfuncs)
    
    # rename columns with function names
    column_names = []
    for func in aggfuncs:
        if func.__name__ == 'mean':
            column_names.append("Mean Daily Return %")
        elif func.__name__ == 'amax':
            column_names.append("Maximum Daily Return %")
        elif func.__name__ == 'amin':
            column_names.append("Minimum Daily Return %")
        elif func.__name__ == 'median':
            column_names.append("Median Daily Return %")
        else:
            column_names.append(f"{func.__name__} Daily Return %")
        
    grouped_returns.columns = column_names
    
    grouped_returns = grouped_returns.rename_axis('Days of the Week')
    grouped_returns = grouped_returns.set_index(pd.Index(["Monday","Tuesday","Wednesday","Thursday","Friday"]))
    grouped_returns[column_names] = grouped_returns[column_names].applymap(lambda x: '{:.3%}'.format(x))
    
    # Count the number of up and down days and add them as new columns
    up_days = symbol[symbol['Daily Return %'] > 0].groupby(symbol.Date.dt.dayofweek)['Daily Return %'].count()
    down_days = symbol[symbol['Daily Return %'] < 0].groupby(symbol.Date.dt.dayofweek)['Daily Return %'].count()
    grouped_returns['Up Days'] = up_days.values
    grouped_returns['Down Days'] = down_days.values
    # Calculate the total number of days for each day of the week
    total_days = symbol.groupby(symbol.Date.dt.dayofweek)['Daily Return %'].size()
    grouped_returns['Total Days'] = total_days.values
    # Calculate the percentage of up and down days
    grouped_returns['% Up Days'] = grouped_returns['Up Days']/ grouped_returns['Total Days']
    grouped_returns['% Up Days'] = grouped_returns['% Up Days'].apply(lambda x: '{:.2%}'.format(x))
    grouped_returns['% Down Days'] = grouped_returns['Down Days']/ grouped_returns['Total Days']
    grouped_returns['% Down Days'] = grouped_returns['% Down Days'].apply(lambda x: '{:.2%}'.format(x))
    return grouped_returns

In [20]:
dayofweek_returns_all_stats(qqq)

,Mean Daily Return %,Maximum Daily Return %,Minimum Daily Return %,Median Daily Return %,Up Days,Down Days,Total Days,% Up Days,% Down Days
Monday,0.004%,14.881%,-6.969%,0.060%,597,528,1135,52.60%,46.52%
Tuesday,-0.046%,7.345%,-8.751%,0.047%,644,585,1241,51.89%,47.14%
Wednesday,0.037%,19.641%,-9.534%,0.069%,652,580,1242,52.50%,46.70%
Thursday,0.050%,8.631%,-7.806%,0.104%,663,545,1221,54.30%,44.64%
Friday,-0.067%,8.787%,-7.645%,0.000%,598,606,1213,49.30%,49.96%

In [21]:
dayofweek_returns_all_stats(spy)

,Mean Daily Return %,Maximum Daily Return %,Minimum Daily Return %,Median Daily Return %,Up Days,Down Days,Total Days,% Up Days,% Down Days
Monday,0.012%,7.968%,-7.470%,0.043%,753,655,1427,52.77%,45.90%
Tuesday,0.001%,9.296%,-6.374%,0.031%,794,746,1559,50.93%,47.85%
Wednesday,0.023%,8.435%,-7.634%,0.069%,836,707,1558,53.66%,45.38%
Thursday,0.005%,5.852%,-8.991%,0.055%,796,719,1530,52.03%,46.99%
Friday,-0.016%,5.117%,-5.661%,0.026%,780,724,1520,51.32%,47.63%

In [28]:
symbol = qqq
symbol['Date'] = pd.to_datetime(symbol['Date'])
symbol.set_index('Date', inplace=True)
symbol['Return'] = (symbol['Close']/symbol['Open'])-1
max_return_date = symbol['Return'].idxmax()
max_return_date

Timestamp('2001-01-03 00:00:00')